apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-rollouts-dev
  namespace: shared-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: dev-only-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: demo-rollouts-{{name}}
    spec:
      destination:
        namespace: demo-rollouts
        server: "{{server}}"
      project: default
      source:
        path: gitops/shared/demo-apps/rollouts-demo/overlays/dev
        repoURL: 'https://github.com/shirodkar/acm-gitops-demo.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-rollouts-qa
  namespace: shared-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: qa-only-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: demo-rollouts-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: shared-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      destination:
        namespace: demo-rollouts
        server: "{{server}}"
      project: default
      source:
        path: gitops/shared/demo-apps/rollouts-demo/overlays/qa
        repoURL: 'https://github.com/shirodkar/acm-gitops-demo.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-rollouts-uat
  namespace: shared-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: uat-only-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: demo-rollouts-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: shared-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      destination:
        namespace: demo-rollouts
        server: "{{server}}"
      project: default
      source:
        path: gitops/shared/demo-apps/rollouts-demo/overlays/uat
        repoURL: 'https://github.com/shirodkar/acm-gitops-demo.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-rollouts-prod
  namespace: shared-gitops
  labels:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-only-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: demo-rollouts-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: shared-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      destination:
        namespace: demo-rollouts
        server: "{{server}}"
      project: default
      source:
        path: gitops/shared/demo-apps/rollouts-demo/overlays/prod
        repoURL: 'https://github.com/shirodkar/acm-gitops-demo.git'
        targetRevision: HEAD
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
      ignoreDifferences:
        - group: route.openshift.io
          kind: Route
          jsonPointers:
            - /spec/to
            - /spec/alternateBackends