apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: quay.io/openshiftdemos/rollouts-demo
    newTag: blue

replicas:
  - name: rollouts-demo
    count: 2


