kind: Deployment
apiVersion: apps/v1
metadata:
  name: rollouts-demo
  labels:
    app: rollouts-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: 'quay.io/openshiftdemos/rollouts-demo:blue'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi