apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments.yaml
  - services.yaml
  - routes.yaml

# common labels applied to all resources in this kustomization
commonLabels:
  app: rollouts-demo

# Keep the image reference here so overlays can easily replace tags if needed
images:
- name: quay.io/openshiftdemos/rollouts-demo
  newTag: blue

