apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-dev
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: dev-only-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: managed-{{name}}
    spec:
      destination:
        server: "{{server}}"
      project: default
      source:
        path: gitops/platform/platform-manifests/managed
        repoURL: 'https://github.com/shirodkar/acm-gitops-demo.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: managedservername
              value: '{{name}}'
            - name: bannercolor
              value: blue
            - name: sharedgitopsurl
              value: 'https://shared-gitops-server-shared-gitops.apps.{{ server | regexReplaceAll "^https?://" "" | regexReplaceAll ":[0-9]+$" "" | regexReplaceAll "^api\\." "" }}'
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-uat
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: uat-only-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: managed-{{name}}
    spec:
      destination:
        server: "{{server}}"
      project: default
      source:
        path: gitops/platform/platform-manifests/managed
        repoURL: 'https://github.com/shirodkar/acm-gitops-demo.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: managedservername
              value: '{{name}}'
            - name: bannercolor
              value: yellow
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: managed-prod
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-only-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: managed-{{name}}
    spec:
      destination:
        server: "{{server}}"
      project: default
      source:
        path: gitops/platform/platform-manifests/managed
        repoURL: 'https://github.com/shirodkar/acm-gitops-demo.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: managedservername
              value: '{{name}}'
            - name: bannercolor
              value: red
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true