apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollouts.yaml
  - services.yaml
  - routes.yaml

images:
  - name: quay.io/openshiftdemos/rollouts-demo
    newTag: blue
