kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: rollouts-demo
  labels:
    app: rollouts-demo
  annotations:
    haproxy.router.openshift.io/disable_cookies: 'true'
    haproxy.router.openshift.io/balance: roundrobin
spec:
  to:
    kind: Service
    name: stable-service
    weight: 100
  alternateBackends:
    - kind: Service
      name: canary-service
      weight: 0
  port:
    targetPort: 8080-tcp