kind: Service
apiVersion: v1
metadata:
  name: stable-service
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: rollouts-demo
---
kind: Service
apiVersion: v1
metadata:
  name: canary-service
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: rollouts-demo